apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        imagePullPolicy: Never
        image: angi
        ports:
        - containerPort: 80
        - containerPort: 443 
---
apiVersion: v1
kind: Service
metadata:
  name: snginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
      # protocol: TCP
      # nodePort: 80
      # targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        imagePullPolicy: Never
        image: ftps
        ports:
        - containerPort: 20
          name: port-21
        - containerPort: 21
          name: port-20
        - containerPort: 31100
          name: port-31100
        - containerPort: 31101
          name: port-31101
        - containerPort: 31102
          name: port-31102
        - containerPort: 31103
          name: port-31103
        - containerPort: 31104
          name: port-31104
        - containerPort: 31105
          name: port-31105
        - containerPort: 31106
          name: port-31106
        - containerPort: 31107
          name: port-31107
        - containerPort: 31108
          name: port-31108
        - containerPort: 31109
          name: port-31109
        - containerPort: 31110
          name: port-31110
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
spec:
  type: NodePort
  selector:
    app: ftps
  ports:
    - name: ftp-31100
      nodePort: 31100
      port: 31100
    - name: ftp-31101
      nodePort: 31101
      port: 31101
    - name: ftp-31102
      nodePort: 31102
      port: 31102
    - name: ftp-31103
      nodePort: 31103
      port: 31103
    - name: ftp-31104
      nodePort: 31104
      port: 31104
    - name: ftp-31105
      nodePort: 31105
      port: 31105
    - name: ftp-31106
      nodePort: 31106
      port: 31106
    - name: ftp-31107
      nodePort: 31107
      port: 31107
    - name: ftp-31108
      nodePort: 31108
      port: 31108
    - name: ftp-31109
      nodePort: 31109
      port: 31109
    - name: ftp-31110
      nodePort: 31110
      port: 31110
    # - name: ftps-svc-20
    #   port: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc2
spec:
  type: ClusterIP
  selector:
    app: ftps
  ports:
    - name: ftp-21
      port: 3500
      targetPort: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        imagePullPolicy: Never
        image: wordpress
        ports:
        - containerPort: 80
          name: port-21
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: http
      port: 80
      nodePort: 5050
---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: snginx
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        imagePullPolicy: Never
        image: mysql
        ports:
        - containerPort: 3306
          name: port-3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: http
      port: 3306
      nodePort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        imagePullPolicy: Never
        image: phpmyadmin
        ports:
        - containerPort: 80
          name: port-80
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - name: http
      port: 80
      nodePort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        imagePullPolicy: Never
        image: influxdb
        ports:
        - containerPort: 8086
          name: port-8086
        - containerPort: 8088
          name: port-8088
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
    - name: port-8086
      port: 8086
      nodePort: 8086
    - name: port-8088
      port: 8088
      nodePort: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        imagePullPolicy: Never
        image: grafana
        ports:
        - containerPort: 3000
          name: port-3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: port-3000
      port: 3000
      nodePort: 3000