USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY "1234" WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
CREATE DATABASE IF NOT EXISTS wpdb CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL ON wpdb.* to wordpress@'%' IDENTIFIED BY '1234';